name: Project Checks

on:
  pull_request:
  workflow_call:
    inputs:
      upload-build:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1.21.1
        with:
          version: 1.0.0
          node-version-file: .node-version
          cache: true
          run-install: |
            args: ["--frozen-lockfile"]

      - name: Check Project
        run: vp run check

      - name: Build Project
        run: vp run docs:build

      - name: Upload Site
        if: inputs.upload-build == true
        uses: actions/upload-artifact@v7
        with:
          name: site-dist
          path: .vitepress/dist
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1
